### ISSUE TITLE
Update to `swf-parser@0.3.0`

### ISSUE THREAD

**Issue by demurgos** [lykenware/flashback#1]
The following libraries got updated:
- [`swf-fixed@0.1.1`](https://github.com/open-flash/rust-swf-fixed/pull/4)
- [`swf-tree@0.4.1`](https://github.com/open-flash/swf-tree/pull/16)
- [`swf-parser@0.3.0`](https://github.com/open-flash/swf-parser/pull/15)

Updating `Cargo.toml` seems to not break the build but I leave the PR to someone with test samples.

**Comment by eddyb** [comment]
It doesn't break the build but I should go in and remove all the unsafe code that does copying of fixed-point values and structs containing them (unless you want to have some fun with that)

**Comment by demurgos** [comment]
I'll leave it for you since you are more familiar with the codebase. :slightly_smiling_face:

**Comment by eddyb** [comment]
Removing the `unsafe` code is sadly not fully possible yet because of https://github.com/open-flash/rust-swf-fixed/issues/5.

But also I can't fully remove the workaround for missing `Copy` impls, because `swf-tree` is missing `Copy` on `Matrix` and `Copy` + `Default` on `ColorTransformWithAlpha` (probably all types that can implement those traits in `swf-tree`, should).

**Comment by demurgos** [comment]
I did a round of updates, here are the latest versions:
- [`swf-fixed@0.1.3`](https://github.com/open-flash/rust-swf-fixed/blob/master/CHANGELOG.md#013-2019-04-05)
- [`swf-tree@0.4.2`](https://github.com/open-flash/swf-tree/pull/21)
- [`swf-parser@0.3.1`](https://github.com/open-flash/swf-parser/pull/19)

**Comment by eddyb** [comment]
Unsafe code is gone in 35fe6ca, I just need to update buttons to use `swf_tree::tag::DefineButton`.
